### PR TITLE
Small improvement in code

### PR DESCRIPTION
**Pull request by LEO1612D**

### CODE REVIEW

**Comment by vikashraghavan** [comment]
image

On apps fresh start,
even on setting the userAccount state as null in constructor and in loadStorage funtion,
on executing executing loadContent the state in not interpreted as null !

Can you please verify it on your side.

**Comment by LEO1612D** [comment]
Sure let me check this

**Comment by LEO1612D** [comment]
Can you check now, the bug raise because of isLogged in storing string value for as 'true' and 'false' which in conditional operation turns down to true every time, so I am converting that string into boolean and storing into isLogged 
Now this bug is resolved it seems.
Please check from your side and do let me know

**Comment by vikashraghavan** [comment]
The bug is fixed.
Thanks for the fix :)

**Pull request merged**
